# Example configuration file for use with urn-randomization package
# To use, rename to config.yaml and edit as necessary

"Example Study":

    # Default values
    # db: sqlite:///urn-randomization.db
    # w: 0
    # alpha: 0
    # beta: 1
    # starting_seed:
    # Possible values include range or variance
    # D: range
    # Method 1 sets p=1 for urn with largest value of D, with random selection in
    # case of tied values
    # urn_selection: method1

    starting_seed: 100
    treatments:
        - 1
        - 2

    factors:
        institute:
            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        pretreatment:
            ["no prior treatment", "prior radiotherapy", "prior chemotherapy"]
        sex:
            [male, female]

"CHS JCOIN HUB":

    # Default values
    # db: sqlite:///urn-randomization.db
    # w: 0
    # alpha: 0
    # beta: 1
    # starting_seed:
    # Possible values include range or variance
    # D: range
    # Method 1 sets p=1 for urn with largest value of D, with random selection in
    # case of tied values
    # urn_selection: method1

    starting_seed: 100
    treatments:
        - MART
        - RMC-Q
        - RMC-A

    factors:
        local_site:
          [ "11=Cook County – Chicago", "30=Dupage County", "40=Grundy County", "50=Mclean County", "60=Tazewell County", "70=Will County" ]
        electronic_monitoring:
          [ "1=Yes", "2=Other" ]
        days_in_jail:
          [ "1=Low (0-12)", "2=Moderate (13-90)", "3=High (91+)" ]
        under_50:
          [ "1=yes (18-49)", "2=Other (50 or older)" ]
        hispanic:
          [ "1=Yes", "2=Other" ]
        african_am :
          [ "1=Yes (including mixed)", "2=Other" ]
        sex:
          [ "1=Male", "2=Other" ]
        overdose_hist:
          [ "1=yes (1+)", "2=No (0)" ]
        prior_sutx:
          [ "1=any MOUD treatment (EU15=1+)", "2= any other SUD treatment [EU10>0]", "3=none" ]
        days_ou:
          [ "1=low (0-12)", "2=moderate(13-44)",  "3=high (45 or more)" ]
        days_stu:
          [ "1=low (0-12)", "2=moderate(13-44)", "3=high (45 or more)" ]
        sud:
          [ "0=low(0)", "2= moderate (1-2)", "3= high (3-5)" ]
        crime_violence:
          [ "1=low (0)", "2=Moderate (1-2)", "3=High (3+)" ]
        com_supervision:
          ["1=yes (>0 days)", "2=other"]


# A short string identifying the study
"CHS JCOIN":

    # Default values
    # db: sqlite:///urn-randomization.db
    # w: 0
    # alpha: 0
    # beta: 1
    # starting_seed:
    # Possible values include range or variance
    # D: range
    # Method 1 sets p=1 for urn with largest value of D, with random selection in
    # case of tied values
    # urn_selection: method1

    starting_seed: 100
    treatments:
        - MART
        - RMC-Q
        - RMC-A

    factors:
        local_site:
            ["11-Cook County – Chicago", "30-Dupage County", "40-Grundy County", "50-Mclean County", "60-Tazewell County", "70-Will County"]
        electronic_monitoring:
            ["Yes", "Other"]
        incarceration_days:
            ["Low (0-12)", "Moderate (13-90)", "High (91+)"]
        young_adult:
            ["Yes (18-25)", "Other (26 or older)"]
        hispanic_descent:
            ["Yes", "Other"]
        african_american:
            ["Yes (including mixed)", "No"]
        sex:
            ["Male", "Female"]
        prior_opioid_overdose:
            ["Yes", "No"]
        prior_substance_use_treatment:
            ["Any MOUD treatment", "Any other SUD treatment", "Other"]
        crime_violence_screener_count:
            ["Low", "Moderate (1-2)",  "High (3-5)"]
        substance_use_days:
            ["Low (0-12)", "Moderate (13-44)", "High"]
        probation_parole_community_supervision:
            ["Yes (1+ days)", "Other"]
        substance_screener_symptoms:
            ["Low", "Moderate (1-2)", "High (3-5)"]