-- SQL Dump of Control.accdb
-- generated by MDB Viewer 2.2.7
-- optimized for SQLite


DROP TABLE IF EXISTS "1a-tbl_BaseClients";

CREATE TABLE "1a-tbl_BaseClients" (
    "Counter" INTEGER,
    "Project" TEXT,
    "ProjectID" INTEGER PRIMARY KEY,
    "RAAssignment" INTEGER,
    "RandomizationDate" DATETIME,
    "Phone_ID" INTEGER,
    "Phone" TEXT,
    "Cohort" TEXT,
    "BaseDate" DATETIME,
    "Baseline_Urine" BOOLEAN,
    "Lastname" TEXT,
    "Firstname" TEXT,
    "Middle" TEXT,
    "SSN" TEXT,
    "DOB" DATETIME,
    "XCHK" TEXT,
    "Comments" TEXT,
    "Ready_Fllwup" BOOLEAN,
    "FolderLabel" BOOLEAN,
    "CaseMgr" INTEGER,
    "SystemDate" DATETIME,
    "Status" INTEGER,
    "LocatorVerified" BOOLEAN,
    "DateVerified" DATETIME,
    "TID" INTEGER
);

INSERT INTO "1a-tbl_BaseClients"("Counter","Project","ProjectID","RAAssignment","RandomizationDate","Phone_ID","Phone","Cohort","BaseDate","Baseline_Urine","Lastname","Firstname","Middle","SSN","DOB","XCHK","Comments","Ready_Fllwup","FolderLabel","CaseMgr","SystemDate","Status","LocatorVerified","DateVerified","TID")
VALUES(2,'SARC-CL',1,2,'2020-01-02 00:00:00',0,NULL,NULL,NULL,0,'Test','Person','A','555555555','1962-01-01 00:00:00',NULL,NULL,0,0,0,'2020-01-28 08:46:30',NULL,0,NULL,0);



DROP TABLE IF EXISTS "2a-tbl_FllwUpClients";

CREATE TABLE "2a-tbl_FllwUpClients" (
    "Counter" INTEGER PRIMARY KEY,
    "ProjectID" INTEGER,
    "Wave" INTEGER,
    "Anniv_Date" DATETIME,
    "ApptDate" DATETIME,
    "ApptTime" DATETIME,
    "ClientStat" INTEGER,
    "UrineStatus" BOOLEAN,
    "CaseMgr" INTEGER,
    "Outreach" BOOLEAN,
    "Comments" TEXT,
    "SystemDate" DATETIME,
    "ParticipationEndStatus" INTEGER,
    "ParticipationDate" DATETIME,
    "NoPhoneAccessReason" INTEGER,
    "NoPhoneAccessDate" DATETIME
);

INSERT INTO "2a-tbl_FllwUpClients"("Counter","ProjectID","Wave","Anniv_Date","ApptDate","ApptTime","ClientStat","UrineStatus","CaseMgr","Outreach","Comments","SystemDate","ParticipationEndStatus","ParticipationDate","NoPhoneAccessReason","NoPhoneAccessDate")
VALUES(1,1,1,'2020-01-08 00:00:00','2020-01-08 00:00:00','1899-12-30 10:00:00',600,0,7879,0,NULL,'2020-01-28 08:47:09',0,NULL,NULL,NULL);
INSERT INTO "2a-tbl_FllwUpClients"("Counter","ProjectID","Wave","Anniv_Date","ApptDate","ApptTime","ClientStat","UrineStatus","CaseMgr","Outreach","Comments","SystemDate","ParticipationEndStatus","ParticipationDate","NoPhoneAccessReason","NoPhoneAccessDate")
VALUES(2,1,2,'2020-01-22 00:00:00','2020-01-20 00:00:00','1899-12-30 10:00:00',175,0,7879,0,NULL,'2020-01-28 08:47:11',0,NULL,NULL,NULL);
INSERT INTO "2a-tbl_FllwUpClients"("Counter","ProjectID","Wave","Anniv_Date","ApptDate","ApptTime","ClientStat","UrineStatus","CaseMgr","Outreach","Comments","SystemDate","ParticipationEndStatus","ParticipationDate","NoPhoneAccessReason","NoPhoneAccessDate")
VALUES(3,1,3,'2020-04-08 00:00:00','2020-04-07 00:00:00','1899-12-30 13:00:00',150,0,7879,0,NULL,'2020-01-28 08:47:58',0,NULL,NULL,NULL);
INSERT INTO "2a-tbl_FllwUpClients"("Counter","ProjectID","Wave","Anniv_Date","ApptDate","ApptTime","ClientStat","UrineStatus","CaseMgr","Outreach","Comments","SystemDate","ParticipationEndStatus","ParticipationDate","NoPhoneAccessReason","NoPhoneAccessDate")
VALUES(4,1,4,'2020-07-08 00:00:00',NULL,NULL,150,0,0,0,NULL,'2020-01-28 08:48:28',0,NULL,NULL,NULL);
INSERT INTO "2a-tbl_FllwUpClients"("Counter","ProjectID","Wave","Anniv_Date","ApptDate","ApptTime","ClientStat","UrineStatus","CaseMgr","Outreach","Comments","SystemDate","ParticipationEndStatus","ParticipationDate","NoPhoneAccessReason","NoPhoneAccessDate")
VALUES(5,1,5,'2020-10-08 00:00:00',NULL,NULL,150,0,0,0,NULL,'2020-01-28 08:48:38',0,NULL,NULL,NULL);



DROP TABLE IF EXISTS "2b-tbl_FllwUpSched";

CREATE TABLE "2b-tbl_FllwUpSched" (
    "Counter" INTEGER PRIMARY KEY,
    "ProjectID" INTEGER,
    "Wave" INTEGER,
    "SchedDate" DATETIME,
    "SchedTime" DATETIME,
    "SchedStatCode" INTEGER,
    "SystemDate" DATETIME
);




DROP TABLE IF EXISTS "2d-tbl_FllwUpEvents";

CREATE TABLE "2d-tbl_FllwUpEvents" (
    "Counter" INTEGER,
    "ProjectID" INTEGER,
    "Wave" INTEGER,
    "Staff_ID" INTEGER,
    "CallPeriod" INTEGER,
    "EventDate" DATETIME,
    "EventTime" DATETIME,
    "Task" INTEGER,
    "Event" INTEGER,
    "Disp" INTEGER,
    "Outc_1" INTEGER,
    "Outc_2" INTEGER,
    "Intvw_Loc" INTEGER,
    "Comments" TEXT,
    "SystemDate" DATETIME
);

INSERT INTO "2d-tbl_FllwUpEvents"("Counter","ProjectID","Wave","Staff_ID","CallPeriod","EventDate","EventTime","Task","Event","Disp","Outc_1","Outc_2","Intvw_Loc","Comments","SystemDate")
VALUES(1,1,-1,5310,0,'2020-01-20 00:00:00','1899-12-30 09:00:00',3,9,19,100,0,0,'test comment','2020-01-23 07:30:51');



DROP TABLE IF EXISTS "2e-tbl_FllwUpContacts";

CREATE TABLE "2e-tbl_FllwUpContacts" (
    "Counter" INTEGER,
    "ProjectID" INTEGER,
    "Relationship" INTEGER,
    "Name" TEXT,
    "Outreach" BOOLEAN,
    "Address-1" TEXT,
    "Address-2" TEXT,
    "City" TEXT,
    "State" TEXT,
    "ZipCode" TEXT,
    "Phone" TEXT,
    "Staff_ID" INTEGER,
    "ContactStatus" INTEGER,
    "MailStatus" INTEGER,
    "IntkThkUCard-date" DATETIME,
    "1mthFlyer-date" DATETIME,
    "2mthFlyer-date" DATETIME,
    "3mthFlyer-date" DATETIME,
    "4mthFlyer-date" DATETIME,
    "5mthFlyer-date" DATETIME,
    "ConfirmFlyerMailDate" DATETIME,
    "Call-inFlyerDate" DATETIME,
    "6m-ThkUCard-date" DATETIME,
    "6w-outkMailDate" DATETIME,
    "Comments" TEXT,
    "SystemDate" DATETIME,
    "PreR_ThkUsent" BOOLEAN,
    "PreR_ThkUSentDate" DATETIME,
    "PreR_Flyer1sent" BOOLEAN,
    "PreR_Flyer1SentDate" DATETIME,
    "PreR_Flyer2sent" BOOLEAN,
    "PreR_Flyer2SentDate" DATETIME
);

INSERT INTO "2e-tbl_FllwUpContacts"("Counter","ProjectID","Relationship","Name","Outreach","Address-1","Address-2","City","State","ZipCode","Phone","Staff_ID","ContactStatus","MailStatus","IntkThkUCard-date","1mthFlyer-date","2mthFlyer-date","3mthFlyer-date","4mthFlyer-date","5mthFlyer-date","ConfirmFlyerMailDate","Call-inFlyerDate","6m-ThkUCard-date","6w-outkMailDate","Comments","SystemDate","PreR_ThkUsent","PreR_ThkUSentDate","PreR_Flyer1sent","PreR_Flyer1SentDate","PreR_Flyer2sent","PreR_Flyer2SentDate")
VALUES(1,1,100,'Test Person',0,'555 w bloomington dr',NULL,'Normal','IL','61701','(309) 555-5555',5310,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2020-01-23 07:30:41',0,NULL,0,NULL,0,NULL);



DROP TABLE IF EXISTS "3a_EMA Survey";

CREATE TABLE "3a_EMA Survey" (
    "Counter" INTEGER PRIMARY KEY,
    "ProjectID" INTEGER,
    "Wave" INTEGER,
    "SurveyDate" DATETIME,
    "StaffID" INTEGER,
    "Q1" INTEGER,
    "Q2" INTEGER,
    "Q3" INTEGER,
    "Q5" INTEGER,
    "Q6" INTEGER,
    "Q7" INTEGER,
    "Q8" INTEGER,
    "Q9" INTEGER,
    "Q10" INTEGER,
    "Q10-difficult" TEXT,
    "Q10a" TEXT,
    "Q11" INTEGER,
    "Q12" INTEGER,
    "Q13" TEXT,
    "Q14" TEXT,
    "Q15" TEXT,
    "System" DATETIME
);




DROP TABLE IF EXISTS "3c_ControlGrp Survey";

CREATE TABLE "3c_ControlGrp Survey" (
    "Counter" INTEGER PRIMARY KEY,
    "ProjectID" INTEGER,
    "Wave" INTEGER,
    "SurveyDate" DATETIME,
    "StaffID" INTEGER,
    "Cohort" INTEGER,
    "Q1" INTEGER,
    "Q1a" INTEGER,
    "Q1b" INTEGER,
    "Q1b_specify" TEXT,
    "Q1c" INTEGER,
    "Q1c-i" INTEGER,
    "Q1c-i_specify" TEXT,
    "Q1d" INTEGER,
    "Q1e" INTEGER,
    "Q1e_specify" TEXT,
    "Q1f" INTEGER,
    "Q1g" INTEGER,
    "Q1h" INTEGER,
    "Q1i" INTEGER,
    "Q1j" INTEGER,
    "Q2" INTEGER,
    "Q2a" INTEGER,
    "Q2a-specify" TEXT,
    "Q2b" INTEGER,
    "Q2c" INTEGER,
    "Q2d" INTEGER,
    "Q3" INTEGER,
    "Q3a" INTEGER,
    "Q3a-specify" TEXT,
    "Q3b" INTEGER,
    "Q3c" INTEGER,
    "Q3d" INTEGER,
    "Q4" INTEGER,
    "Q4a" INTEGER,
    "Q4b" INTEGER,
    "Q4c" INTEGER,
    "Q4d" INTEGER,
    "Q4e" INTEGER,
    "Q5" INTEGER,
    "Q5a" INTEGER,
    "Q5b" INTEGER,
    "Q5c" INTEGER,
    "Q5d" INTEGER,
    "Q6-1" INTEGER,
    "Q6-2" INTEGER,
    "Q6-3" INTEGER,
    "Q6-4" INTEGER,
    "Q6-5" INTEGER,
    "Q7" INTEGER,
    "Q7-specify" TEXT,
    "System" DATETIME
);




DROP TABLE IF EXISTS "3d_UrineResults";

CREATE TABLE "3d_UrineResults" (
    "Counter" INTEGER PRIMARY KEY,
    "ProjectID" INTEGER,
    "Wave" INTEGER,
    "Date" DATETIME,
    "StaffID" INTEGER,
    "U1" INTEGER,
    "U2" INTEGER,
    "U2v" TEXT,
    "U2a" INTEGER,
    "U2av" TEXT,
    "U3_Time" TEXT,
    "U3a_Time" DATETIME,
    "U3b_Temperature" INTEGER,
    "U34_Time" DATETIME,
    "U4v" TEXT,
    "U5-OXI_AdSamp" INTEGER,
    "U5-SGAdSamp" INTEGER,
    "U5-pHAdSamp" INTEGER,
    "U5-NITAdSamp" INTEGER,
    "U5-GLUTAdSamp" INTEGER,
    "U5-CREAAdSamp" INTEGER,
    "U6_FEN" INTEGER,
    "U6_ETG" INTEGER,
    "U6_K2" INTEGER,
    "U6_TRA" INTEGER,
    "U6_THC" INTEGER,
    "U6_BUP" INTEGER,
    "U6_BAR" INTEGER,
    "U6_BZO" INTEGER,
    "U6_MTD" INTEGER,
    "U6_AMP" INTEGER,
    "U6_OXY" INTEGER,
    "U6_OPI" INTEGER,
    "U6_MDMA" INTEGER,
    "U6_COC" INTEGER,
    "U6_PCP" INTEGER,
    "U6_MET" INTEGER,
    "U7_BreathalyzerResults" DOUBLE,
    "Notes" TEXT,
    "AdulteratedSample_Old form" INTEGER,
    "U3_OLD Form data" INTEGER
);




DROP TABLE IF EXISTS "8a_Phones";

CREATE TABLE "8a_Phones" (
    "Ph_ID" INTEGER PRIMARY KEY,
    "Wireless Number" TEXT,
    "Status" INTEGER,
    "ProjectID" INTEGER,
    "TID" INTEGER,
    "DateAssigned" DATETIME,
    "DateRemoved-Field" DATETIME,
    "Gmail" TEXT,
    "Password" TEXT,
    "IMEI" TEXT,
    "SIM" TEXT,
    "SIM-6" TEXT,
    "SystemDate" DATETIME,
    "Comments" TEXT
);

INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(1,'309-386-3716',0,0,0,NULL,NULL,NULL,NULL,'353425085216689','89148000005530950062 ','950062 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(2,'309-386-3847',0,0,0,NULL,NULL,NULL,NULL,'355301071999026','89148000005530880848 ','880848 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(3,'309-386-4061',0,0,0,NULL,NULL,NULL,NULL,'356354081161854','89148000005530881572 ','881572 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(4,'309-386-3971',0,0,0,NULL,NULL,NULL,NULL,'359764083164127','89148000005530880772 ','880772 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(5,'309-386-3966',0,0,0,NULL,NULL,NULL,NULL,'359775078196676','89148000005530880780 ','880780 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(6,'309-386-3782',0,0,0,NULL,NULL,NULL,NULL,'359775078196775','89148000005530880871 ','880871 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(7,'309-386-3769',0,0,0,NULL,NULL,NULL,NULL,'359775078199779','89148000005530880889 ','880889 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(8,'309-386-9952',0,0,0,NULL,NULL,NULL,NULL,'359775078199803','89148000005530880970 ','880970 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(9,'309-386-4113',0,0,0,NULL,NULL,NULL,NULL,'359775078199811','89148000005530881507 ','881507 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(10,'309-386-3850',0,0,0,NULL,NULL,NULL,NULL,'359775078199837','89148000005530880822 ','880822 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(11,'309-386-4026',0,0,0,NULL,NULL,NULL,NULL,'359775078199878','89148000005530880764 ','880764 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(12,'309-386-3921',0,0,0,NULL,NULL,NULL,NULL,'359775078199886','89148000005530949858 ','949858 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(13,'309-386-3833',0,0,0,NULL,NULL,NULL,NULL,'359775078199985','89148000005530950047 ','950047 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(14,'309-386-8076',0,0,0,NULL,NULL,NULL,NULL,'359775078200049','89148000005530880921 ','880921 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(15,'309-386-3946',0,0,0,NULL,NULL,NULL,NULL,'359775078200320','89148000005530880806 ','880806 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(16,'309-386-3842',0,0,0,NULL,NULL,NULL,NULL,'359775078244658','89148000005530950138 ','950138 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(17,'309-386-3609',0,0,0,NULL,NULL,NULL,NULL,'359775078244823','89148000005530880913 ','880913 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(18,'309-386-3963',0,0,0,NULL,NULL,NULL,NULL,'359775078245036','89148000005530880798 ','880798 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(19,'309-386-3826',0,0,0,NULL,NULL,NULL,NULL,'359775078245218','89148000005530880855 ','880855 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(20,'309-386-3794',0,0,0,NULL,NULL,NULL,NULL,'359775078245242','89148000005530950054 ','950054 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(21,'309-386-3739',0,0,0,NULL,NULL,NULL,NULL,'359775078245291','89148000005530880905 ','880905 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(22,'309-386-3893',0,0,0,NULL,NULL,NULL,NULL,'359775078245358','89148000005530880814 ','880814 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(23,'309-386-4128',0,0,0,NULL,NULL,NULL,NULL,'359775078245481','89148000005530881499 ','881499 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(24,'309-386-3745',0,0,0,NULL,NULL,NULL,NULL,'359775078245960','89148000005530880897 ','880897 ','2020-01-03 00:00:00',NULL);
INSERT INTO "8a_Phones"("Ph_ID","Wireless Number","Status","ProjectID","TID","DateAssigned","DateRemoved-Field","Gmail","Password","IMEI","SIM","SIM-6","SystemDate","Comments")
VALUES(25,'309-386-3800',0,0,0,NULL,NULL,NULL,NULL,'359775078251554','89148000005530880863 ','880863 ','2020-01-03 00:00:00',NULL);



DROP TABLE IF EXISTS "tbl-1a_Screener";

CREATE TABLE "tbl-1a_Screener" (
    "ProjectID" INTEGER PRIMARY KEY,
    "Project" TEXT,
    "SF0" TEXT,
    "LNAME" TEXT,
    "FNAME" TEXT,
    "ScreeningSite" INTEGER,
    "ScreeningSite-Other" TEXT,
    "AdmitDate" DATETIME,
    "XSID" INTEGER,
    "XSN" TEXT,
    "XSCRDT" DATETIME,
    "SF1" INTEGER,
    "SF1a" INTEGER,
    "SF2_1" INTEGER,
    "SF2_2" INTEGER,
    "SF2_3" INTEGER,
    "SF2_Specify" TEXT,
    "SF3" INTEGER,
    "SF3_Other" TEXT,
    "SF3_Specify" TEXT,
    "SF3a" INTEGER,
    "SF3b" INTEGER,
    "SF3c" INTEGER,
    "SF3d" INTEGER,
    "SF3e" INTEGER,
    "SF3f" INTEGER,
    "SF3h" INTEGER,
    "SF3i" INTEGER,
    "SF3j" INTEGER,
    "SF3k" INTEGER,
    "EligibilityStatus" INTEGER,
    "SystemDate" DATETIME,
    "AnticipatedDischargeDate" DATETIME,
    "ResidentialDisp" INTEGER,
    "TrainingInviteDisp" INTEGER,
    "TrainingInviteIneligReason" INTEGER,
    "TrainingSchedDate" DATETIME,
    "TrainingSchedDisp" INTEGER,
    "TrainingDisp" INTEGER,
    "SU1a" INTEGER,
    "SU1b" INTEGER,
    "SU1c" INTEGER,
    "SU1d" INTEGER,
    "SU1e" INTEGER,
    "SU1f" INTEGER
);

INSERT INTO "tbl-1a_Screener"("ProjectID","Project","SF0","LNAME","FNAME","ScreeningSite","ScreeningSite-Other","AdmitDate","XSID","XSN","XSCRDT","SF1","SF1a","SF2_1","SF2_2","SF2_3","SF2_Specify","SF3","SF3_Other","SF3_Specify","SF3a","SF3b","SF3c","SF3d","SF3e","SF3f","SF3h","SF3i","SF3j","SF3k","EligibilityStatus","SystemDate","AnticipatedDischargeDate","ResidentialDisp","TrainingInviteDisp","TrainingInviteIneligReason","TrainingSchedDate","TrainingSchedDisp","TrainingDisp","SU1a","SU1b","SU1c","SU1d","SU1e","SU1f")
VALUES(1,'SARC-CL','a','Test','Person',22,NULL,NULL,5310,'Belinda','2020-01-19 00:00:00',0,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'2020-01-23 00:00:00',NULL,0,0,0,NULL,0,0,0,0,0,0,0,0);



DROP TABLE IF EXISTS "tbl-2b_Release-Contact";

CREATE TABLE "tbl-2b_Release-Contact" (
    "Counter" INTEGER PRIMARY KEY,
    "ProjectID" INTEGER,
    "ContactStatus" INTEGER,
    "ParticipantName" TEXT,
    "CellPhone" TEXT,
    "HomePhone" TEXT,
    "Phone3" TEXT,
    "Ph3-Name" TEXT,
    "BestTime" INTEGER,
    "Address_1" TEXT,
    "Address_2" TEXT,
    "City" TEXT,
    "State" TEXT,
    "Zipcode" TEXT,
    "PreR_ThkUsent" BOOLEAN,
    "PreR_ThkUSentDate" DATETIME,
    "PreR_Flyer1sent" BOOLEAN,
    "PreR_Flyer1SentDate" DATETIME,
    "PreR_Flyer2sent" BOOLEAN,
    "PreR_Flyer2SentDate" DATETIME,
    "Other-name_phone" TEXT
);

INSERT INTO "tbl-2b_Release-Contact"("Counter","ProjectID","ContactStatus","ParticipantName","CellPhone","HomePhone","Phone3","Ph3-Name","BestTime","Address_1","Address_2","City","State","Zipcode","PreR_ThkUsent","PreR_ThkUSentDate","PreR_Flyer1sent","PreR_Flyer1SentDate","PreR_Flyer2sent","PreR_Flyer2SentDate","Other-name_phone")
VALUES(1,1,1,'Test Person','3095555555',NULL,NULL,NULL,1,'555 w bloomington drive',NULL,'normail','il','61701',0,NULL,0,NULL,0,NULL,NULL);



DROP TABLE IF EXISTS "tbl-3a_TrainingSched";

CREATE TABLE "tbl-3a_TrainingSched" (
    "Counter" INTEGER PRIMARY KEY,
    "ProjectID" INTEGER,
    "SchedDate" DATETIME,
    "SchedStatCode" INTEGER,
    "SystemDate" DATETIME
);




DROP TABLE IF EXISTS "x1a_Tr-InviteDisp";

CREATE TABLE "x1a_Tr-InviteDisp" (
    "TRI-Code" INTEGER PRIMARY KEY,
    "Tr_Disp" TEXT
);

INSERT INTO "x1a_Tr-InviteDisp"("TRI-Code","Tr_Disp")
VALUES(0,'Pending');
INSERT INTO "x1a_Tr-InviteDisp"("TRI-Code","Tr_Disp")
VALUES(1,'Invited');
INSERT INTO "x1a_Tr-InviteDisp"("TRI-Code","Tr_Disp")
VALUES(2,'Refused');
INSERT INTO "x1a_Tr-InviteDisp"("TRI-Code","Tr_Disp")
VALUES(3,'Outside window');
INSERT INTO "x1a_Tr-InviteDisp"("TRI-Code","Tr_Disp")
VALUES(4,'Deceased');
INSERT INTO "x1a_Tr-InviteDisp"("TRI-Code","Tr_Disp")
VALUES(5,'Not Eligible');



DROP TABLE IF EXISTS "x1b_IneligReasons";

CREATE TABLE "x1b_IneligReasons" (
    "I-Code" INTEGER PRIMARY KEY,
    "Reason" TEXT
);

INSERT INTO "x1b_IneligReasons"("I-Code","Reason")
VALUES(0,NULL);
INSERT INTO "x1b_IneligReasons"("I-Code","Reason")
VALUES(100,'Incarcerated');
INSERT INTO "x1b_IneligReasons"("I-Code","Reason")
VALUES(101,'Lives outside Chicago');
INSERT INTO "x1b_IneligReasons"("I-Code","Reason")
VALUES(102,'Duplicate');
INSERT INTO "x1b_IneligReasons"("I-Code","Reason")
VALUES(103,'Reports no SUD-90 days');



DROP TABLE IF EXISTS "x2a_Disposition";

CREATE TABLE "x2a_Disposition" (
    "Disp_Code" INTEGER PRIMARY KEY,
    "Disposition" TEXT
);

INSERT INTO "x2a_Disposition"("Disp_Code","Disposition")
VALUES(0,NULL);
INSERT INTO "x2a_Disposition"("Disp_Code","Disposition")
VALUES(1,'Pending');
INSERT INTO "x2a_Disposition"("Disp_Code","Disposition")
VALUES(2,'Rescheduled');
INSERT INTO "x2a_Disposition"("Disp_Code","Disposition")
VALUES(3,'No Show');
INSERT INTO "x2a_Disposition"("Disp_Code","Disposition")
VALUES(10,'Showed-Randomized');
INSERT INTO "x2a_Disposition"("Disp_Code","Disposition")
VALUES(20,'Outside Window');
INSERT INTO "x2a_Disposition"("Disp_Code","Disposition")
VALUES(40,'Deceased');
INSERT INTO "x2a_Disposition"("Disp_Code","Disposition")
VALUES(50,'Incarcerated');
INSERT INTO "x2a_Disposition"("Disp_Code","Disposition")
VALUES(60,'Not randomized-Refused');
INSERT INTO "x2a_Disposition"("Disp_Code","Disposition")
VALUES(65,'Not randomized-Lives outside Chicago');



DROP TABLE IF EXISTS "x2b_ResidDisp";

CREATE TABLE "x2b_ResidDisp" (
    "R-Disp" INTEGER PRIMARY KEY,
    "ResidDisp" TEXT
);

INSERT INTO "x2b_ResidDisp"("R-Disp","ResidDisp")
VALUES(0,NULL);
INSERT INTO "x2b_ResidDisp"("R-Disp","ResidDisp")
VALUES(300,'In treatment');
INSERT INTO "x2b_ResidDisp"("R-Disp","ResidDisp")
VALUES(301,'Discharged');



DROP TABLE IF EXISTS "x3a_Tr-SchedDisp";

CREATE TABLE "x3a_Tr-SchedDisp" (
    "TrSc-Disp" INTEGER PRIMARY KEY,
    "SchedDisp" TEXT
);

INSERT INTO "x3a_Tr-SchedDisp"("TrSc-Disp","SchedDisp")
VALUES(0,'Scheduled');
INSERT INTO "x3a_Tr-SchedDisp"("TrSc-Disp","SchedDisp")
VALUES(200,'Showed');
INSERT INTO "x3a_Tr-SchedDisp"("TrSc-Disp","SchedDisp")
VALUES(201,'No Show');
INSERT INTO "x3a_Tr-SchedDisp"("TrSc-Disp","SchedDisp")
VALUES(202,'Rescheduled');



DROP TABLE IF EXISTS "x4a_Site";

CREATE TABLE "x4a_Site" (
    "S-Code" INTEGER PRIMARY KEY,
    "Site" TEXT
);

INSERT INTO "x4a_Site"("S-Code","Site")
VALUES(21,'Phone');
INSERT INTO "x4a_Site"("S-Code","Site")
VALUES(22,'In Person');
INSERT INTO "x4a_Site"("S-Code","Site")
VALUES(23,'Internet');
INSERT INTO "x4a_Site"("S-Code","Site")
VALUES(99,'Other');



DROP TABLE IF EXISTS "z-tbl_PhoneStatus";

CREATE TABLE "z-tbl_PhoneStatus" (
    "P-code" INTEGER PRIMARY KEY,
    "P-status" TEXT
);

INSERT INTO "z-tbl_PhoneStatus"("P-code","P-status")
VALUES(10,'Active-unassigned');
INSERT INTO "z-tbl_PhoneStatus"("P-code","P-status")
VALUES(11,'Active-assigned');
INSERT INTO "z-tbl_PhoneStatus"("P-code","P-status")
VALUES(15,'Inactive (Stored)');
INSERT INTO "z-tbl_PhoneStatus"("P-code","P-status")
VALUES(20,'Stolen-suspended');
INSERT INTO "z-tbl_PhoneStatus"("P-code","P-status")
VALUES(30,'Lost-suspended');
INSERT INTO "z-tbl_PhoneStatus"("P-code","P-status")
VALUES(40,'Incarcerated-suspended');
INSERT INTO "z-tbl_PhoneStatus"("P-code","P-status")
VALUES(50,'Broken');
INSERT INTO "z-tbl_PhoneStatus"("P-code","P-status")
VALUES(60,NULL);
INSERT INTO "z-tbl_PhoneStatus"("P-code","P-status")
VALUES(75,'Participation ended-returned');



DROP TABLE IF EXISTS "z-tbl_RAStatusCodes";

CREATE TABLE "z-tbl_RAStatusCodes" (
    "AssgCode" INTEGER PRIMARY KEY,
    "Assignment" TEXT
);

INSERT INTO "z-tbl_RAStatusCodes"("AssgCode","Assignment")
VALUES(0,NULL);
INSERT INTO "z-tbl_RAStatusCodes"("AssgCode","Assignment")
VALUES(1,'Control');
INSERT INTO "z-tbl_RAStatusCodes"("AssgCode","Assignment")
VALUES(2,'SARC');



DROP TABLE IF EXISTS "z-tbl_Staff";

CREATE TABLE "z-tbl_Staff" (
    "Staff-ID" INTEGER PRIMARY KEY,
    "S_First" TEXT,
    "S_Last" TEXT,
    "AbbrvID" TEXT,
    "Intvwr" BOOLEAN,
    "CaseMgr" BOOLEAN,
    "LinkageMgr" BOOLEAN,
    "Inactive" BOOLEAN,
    "Lineup" INTEGER
);

INSERT INTO "z-tbl_Staff"("Staff-ID","S_First","S_Last","AbbrvID","Intvwr","CaseMgr","LinkageMgr","Inactive","Lineup")
VALUES(5310,'Belinda',NULL,NULL,0,0,0,0,0);



DROP TABLE IF EXISTS "zFllw-up-tbl_A-TasksCodes";

CREATE TABLE "zFllw-up-tbl_A-TasksCodes" (
    "TaskCode" INTEGER,
    "Task" TEXT
);

INSERT INTO "zFllw-up-tbl_A-TasksCodes"("TaskCode","Task")
VALUES(1,'Verification');
INSERT INTO "zFllw-up-tbl_A-TasksCodes"("TaskCode","Task")
VALUES(2,'Confirmation');
INSERT INTO "zFllw-up-tbl_A-TasksCodes"("TaskCode","Task")
VALUES(4,'Regular Mailings');
INSERT INTO "zFllw-up-tbl_A-TasksCodes"("TaskCode","Task")
VALUES(3,'Reminder Calls/Contacts');
INSERT INTO "zFllw-up-tbl_A-TasksCodes"("TaskCode","Task")
VALUES(5,'Interview');
INSERT INTO "zFllw-up-tbl_A-TasksCodes"("TaskCode","Task")
VALUES(6,'Information calls');
INSERT INTO "zFllw-up-tbl_A-TasksCodes"("TaskCode","Task")
VALUES(7,'Record search');
INSERT INTO "zFllw-up-tbl_A-TasksCodes"("TaskCode","Task")
VALUES(8,'Internet search');
INSERT INTO "zFllw-up-tbl_A-TasksCodes"("TaskCode","Task")
VALUES(0,NULL);



DROP TABLE IF EXISTS "zFllw-up-tbl_B-EventCodes";

CREATE TABLE "zFllw-up-tbl_B-EventCodes" (
    "EvntCode" INTEGER,
    "Event" TEXT,
    "Task" INTEGER
);

INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(1,'Calls',1);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(2,'Mailing',1);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(3,'Fax',1);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(4,'Outreach',1);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(5,'Calls',2);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(6,'Mailing',2);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(7,'Fax',2);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(8,'Outreach',2);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(9,'Calls',3);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(10,'Mailings',3);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(11,'Outreach',3);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(12,'Mailing',4);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(13,'Face-to-face',5);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(14,'Telephone',5);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(15,'Calls',6);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(16,'Internet',7);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(17,'Internet',8);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(18,'Lexis Nexis',2);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(19,'Pick-up',5);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(20,'Internet search',1);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(40,'Text',3);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(41,'Email',3);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(21,'CCJ',8);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(22,'IDOC',8);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(23,'Vinelink',8);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(24,'Contact agency',1);
INSERT INTO "zFllw-up-tbl_B-EventCodes"("EvntCode","Event","Task")
VALUES(25,'Social media search',1);



DROP TABLE IF EXISTS "zFllw-up-tbl_C-DispositionCodes";

CREATE TABLE "zFllw-up-tbl_C-DispositionCodes" (
    "DispCode" INTEGER,
    "Disposition" TEXT,
    "Event" INTEGER
);

INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(1,'Answered',1);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(2,'Received a call',1);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(3,'Not answered',1);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(4,'Sent',2);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(7,'Received',3);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(8,'Residence',4);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(5,'Returned',2);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(6,'Sent',3);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(9,'Field',4);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(10,'Answered',5);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(11,'Received a call',5);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(12,'Not answered',5);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(13,'Sent',6);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(14,'Returned',6);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(15,'Sent',7);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(16,'Received',7);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(17,'Residence',8);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(18,'Field',8);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(19,'Answered',9);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(20,'Received call',9);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(21,'Not answered',9);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(22,'Sent',10);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(23,'Returned',10);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(24,'Residence',11);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(25,'Field',11);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(26,'Sent',12);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(27,'Received response card',12);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(28,'Returned',12);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(29,'Completed',13);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(30,'Not completed',13);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(31,'Completed',14);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(32,'Not completed',14);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(33,'Received a call',15);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(34,'Connection made',16);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(35,'No connection',16);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(36,'Connection made',17);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(37,'No connection',17);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(38,'Connected',18);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(39,'Not connected',18);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(40,'Field',19);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(41,'Residence',19);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(42,'Found info',20);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(43,'Info not found',20);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(74,'Sent',40);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(75,'Returned',40);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(76,'Sent',41);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(77,'Returned',41);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(45,'Connected',21);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(46,'Not connected',21);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(47,'Connected',22);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(48,'Not connected',22);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(49,'Connected',23);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(50,'Not connected',23);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(51,'Checked Haymarket database',24);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(52,'Spoke with agency staff',24);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(53,'Connected',25);
INSERT INTO "zFllw-up-tbl_C-DispositionCodes"("DispCode","Disposition","Event")
VALUES(54,'Not connected',25);



DROP TABLE IF EXISTS "zFllw-up-tbl_D-OutcomeCodes";

CREATE TABLE "zFllw-up-tbl_D-OutcomeCodes" (
    "OutCode" INTEGER,
    "Outcome" TEXT,
    "Disp" INTEGER
);

INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(110,'Raised reimbursement amount',20);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(111,'Offered bounty',20);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(112,'Refused',20);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(113,'Converted',20);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(115,'Reminded ptp',20);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(116,'Left message',20);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(197,'Bad address client',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(198,'Bad number collateral',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(199,'Bad number client',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(145,'No forwarding address stamp',28);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(146,'New forwarding address',28);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(216,'Uncooperative collateral',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(200,'Scheduled',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(201,'Scheduled',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(84,'Refused',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(85,'Converted',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(1,'Left message',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(2,'Verified client info',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(3,'Verified collateral info',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(4,'New client info',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(5,'New collateral info',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(8,'Verified client info',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(9,'Verified collateral info',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(10,'New client info',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(11,'New collateral info',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(12,'Refused',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(13,'Rescheduled',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(14,'No answer',3);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(15,'Busy',3);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(16,'Disconnected',3);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(17,'Client',4);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(18,'Collateral',4);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(19,'New forwarding address',5);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(20,'No forwarding address stamp',5);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(22,'Yes',6);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(23,'Yes',7);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(24,'Verified client info',8);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(25,'Verified collateral info',8);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(26,'No one home',8);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(27,'Left flyer',8);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(28,'New info',8);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(29,'Verified client info',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(30,'Verified collateral info',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(31,'New info',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(32,'Left flyer',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(34,'Left message',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(36,'Confirmed w/ supervisor',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(37,'Confirmed w/o supervisor',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(38,'New info',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(39,'Rescheduled',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(40,'Raised reimbursement',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(41,'Offered bounty',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(42,'Refused',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(74,'No one home',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(86,'Refused',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(87,'Converted',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(88,'Rescheduled',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(89,'Converted',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(90,'Left message',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(91,'Offered bounty',8);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(92,'Refused',8);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(94,'Offered bounty',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(95,'Refused',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(97,'Left message',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(98,'Left message',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(100,'New info',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(101,'Rescheduled',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(102,'Raised reimbursement amount',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(103,'Offered bounty',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(104,'Refused',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(105,'Converted',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(107,'Reminded ptp',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(108,'New info',20);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(109,'Rescheduled',20);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(207,'Schedule card',4);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(215,'Uncooperative collateral',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(43,'Converted',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(45,'Confirmed w/ supervisor',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(46,'Confirmed w/o supervisor',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(47,'New info',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(225,'Prepare for outreach',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(226,'Prepare for outreach',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(202,'Bad address collateral',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(203,'Bad address client',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(204,'Bad address collateral',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(205,'Bad address client',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(206,'Scheduled',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(217,'Uncooperative collateral',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(218,'Uncooperative collateral',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(166,'Thank you card',26);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(167,'Confirmation letter',26);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(168,'PreFllwup 4-mth Rem flyer',26);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(169,'PreFllwup 3-mth Rem flyer',26);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(170,'PreFllwup 2-mth Response card',26);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(0,NULL,0);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(171,'Bad number client',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(172,'Bad number collateral',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(173,'Bad address client',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(174,'Bad address collateral',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(175,'Scheduled',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(176,'No recent contact',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(177,'Scheduled',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(178,'No recent contact',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(179,'Bad number client',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(180,'Bad number collateral',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(181,'Bad address client',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(182,'Bad address collateral',2);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(33,'Nothing new',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(79,'Nothing new',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(183,'Bad number client',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(184,'Bad number collateral',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(185,'Bad address client',8);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(186,'Bad address collateral',8);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(187,'Scheduled',8);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(188,'Scheduled',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(189,'Bad address client',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(190,'Bad address collateral',9);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(191,'Bad number client',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(192,'Bad number collateral',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(193,'Bad address client',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(194,'Bad address collateral',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(195,'Scheduled',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(196,'Bad address collateral',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(76,'Confirmed w/o supervisor',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(77,'Rescheduled',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(80,'New info',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(81,'Raised reimbursement amount',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(82,'Offered bounty',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(219,'Uncooperative collateral',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(220,'Uncooperative collateral',20);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(221,'No recent contact',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(222,'Unable to leave message',10);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(223,'Unable to leave message',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(224,'Unable to leave message',19);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(48,'Rescheduled',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(49,'Raised reimbursement',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(50,'Offered bounty',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(51,'Refused',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(53,'No answer',12);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(54,'Busy',12);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(55,'Disconnected',12);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(56,'Letter',13);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(57,'Schedule card',13);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(58,'No forwarding address stamp',14);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(60,'New forwarding address',14);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(61,'Yes',15);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(62,'Yes',16);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(64,'Left flyer',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(65,'Confirmed w/supervisor',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(66,'Confirmed w/o supervisor',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(67,'Rescheduled',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(69,'Raised reimbursement',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(70,'Offered bounty',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(72,'Refused',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(73,'Converted',17);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(75,'Confirmed w/supervisor',18);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(117,'No answer',21);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(118,'Busy',21);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(119,'Disconnected',21);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(120,'Yes',22);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(121,'No forwarding address stamp',23);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(122,'New forwarding address',23);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(125,'Left flyer',24);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(126,'Rescheduled',24);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(127,'New info',24);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(128,'Raised reimbursement amount',24);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(129,'Offered bounty',24);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(131,'Refused',24);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(132,'Converted',24);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(133,'No one home',24);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(134,'Rescheduled',25);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(136,'Nothing new',25);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(137,'New info',25);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(138,'Raised reimbursement amount',25);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(139,'Offered bounty',25);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(141,'Refused',25);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(142,'Converted',25);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(143,'Same address',27);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(144,'New address',27);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(235,'Flyer',13);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(236,'Confirmation flyer',13);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(243,'Appointment Postcard',13);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(241,'Postcard confirmed w/ supervisor',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(242,'Postcard confirmed w/o supervisor',11);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(148,'With saliva',29);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(149,'Without saliva',29);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(150,'Refused urine',29);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(151,'ID verified',29);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(152,'ID verification attempted',29);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(153,'Partial refused',30);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(154,'Partial rescheduled',30);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(155,'Terminated',30);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(156,'Failed ID verification',30);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(157,'With urine',31);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(158,'Without urine',31);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(159,'Refused urine',31);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(160,'ID verified',31);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(161,'ID verification attempted',31);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(162,'Partial refused',32);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(163,'Partial rescheduled',32);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(164,'Terminated',32);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(165,'Failed ID verification',32);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(227,'Treatment referral',33);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(228,'Rescheduled',33);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(229,'Located',34);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(230,'Not located',34);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(231,'Located',36);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(232,'Not located',36);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(233,'No connection',35);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(234,'No connection',37);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(237,'New Info-client',38);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(238,'New Info-collateral',38);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(239,'Not found',38);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(240,'Not found',39);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(244,'Brought to office',40);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(245,'Brought to office',41);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(246,'Verified info',42);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(247,'Not verified',43);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(248,'Not verified',42);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(249,'Reminded ptp',1);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(250,'New Info-client',45);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(251,'Not found',45);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(252,'New Info-client',47);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(253,'Not found',47);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(254,'New Info-client',49);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(255,'Not found',49);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(256,'Not found',46);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(324,'Client',73);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(325,'Collateral',73);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(322,'New forwarding address',72);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(323,'No forwarding address stamp',72);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(318,'New forwarding address',70);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(319,'No forwarding address stamp',70);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(320,'Client',71);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(321,'Collateral',71);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(326,'Interview not conducted',30);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(327,'Interview not conducted',32);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(257,'Not found',48);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(258,'Not found',50);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(259,'Info verified',51);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(260,'Info not verified',51);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(261,'Info verified',52);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(262,'Info not verified',52);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(263,'Info verified',53);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(264,'Info not verified',53);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(265,'Not found',54);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(328,'Yes',74);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(329,'No',74);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(330,'Made Contact',75);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(331,'Email sent',76);
INSERT INTO "zFllw-up-tbl_D-OutcomeCodes"("OutCode","Outcome","Disp")
VALUES(332,'Email returned',77);



DROP TABLE IF EXISTS "zFllw-up-tbl_E-CallPeriodCodes";

CREATE TABLE "zFllw-up-tbl_E-CallPeriodCodes" (
    "PeriodCode" INTEGER,
    "Period" TEXT
);

INSERT INTO "zFllw-up-tbl_E-CallPeriodCodes"("PeriodCode","Period")
VALUES(1,'4-wk');
INSERT INTO "zFllw-up-tbl_E-CallPeriodCodes"("PeriodCode","Period")
VALUES(2,'7-day');
INSERT INTO "zFllw-up-tbl_E-CallPeriodCodes"("PeriodCode","Period")
VALUES(3,'24-hr');
INSERT INTO "zFllw-up-tbl_E-CallPeriodCodes"("PeriodCode","Period")
VALUES(4,'NA');
INSERT INTO "zFllw-up-tbl_E-CallPeriodCodes"("PeriodCode","Period")
VALUES(0,'Missing');
INSERT INTO "zFllw-up-tbl_E-CallPeriodCodes"("PeriodCode","Period")
VALUES(5,'3-wk');
INSERT INTO "zFllw-up-tbl_E-CallPeriodCodes"("PeriodCode","Period")
VALUES(6,'30-day CCC');
INSERT INTO "zFllw-up-tbl_E-CallPeriodCodes"("PeriodCode","Period")
VALUES(7,'90-day CCC');
INSERT INTO "zFllw-up-tbl_E-CallPeriodCodes"("PeriodCode","Period")
VALUES(8,'150-day CCC');



DROP TABLE IF EXISTS "zFllw-up-tbl_F-IntvwLocCodes";

CREATE TABLE "zFllw-up-tbl_F-IntvwLocCodes" (
    "LocCode" INTEGER,
    "Location" TEXT,
    "Task" INTEGER
);

INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(13,'IDOC',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(12,'CCJ',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(15,'Client''s Home',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(16,'Tx Facility',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(17,'Hospital',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(18,'Other',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(11,'Lighthouse',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(19,'Public area',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(10,'Recovery Point',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(20,'Out of state prison',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(21,'Federal prison',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(14,'Collateral''s home',5);
INSERT INTO "zFllw-up-tbl_F-IntvwLocCodes"("LocCode","Location","Task")
VALUES(0,NULL,0);



DROP TABLE IF EXISTS "zFllw-up-tbl_G-FLFcodes";

CREATE TABLE "zFllw-up-tbl_G-FLFcodes" (
    "FLFcodes" INTEGER,
    "FLF_Status" TEXT,
    "Abrv" TEXT
);

INSERT INTO "zFllw-up-tbl_G-FLFcodes"("FLFcodes","FLF_Status","Abrv")
VALUES(0,'Unverified',NULL);
INSERT INTO "zFllw-up-tbl_G-FLFcodes"("FLFcodes","FLF_Status","Abrv")
VALUES(1,'Verified',NULL);
INSERT INTO "zFllw-up-tbl_G-FLFcodes"("FLFcodes","FLF_Status","Abrv")
VALUES(2,'Problem',NULL);
INSERT INTO "zFllw-up-tbl_G-FLFcodes"("FLFcodes","FLF_Status","Abrv")
VALUES(-1,'Verified','Verified');
INSERT INTO "zFllw-up-tbl_G-FLFcodes"("FLFcodes","FLF_Status","Abrv")
VALUES(3,'No good contacts','No good contacts');



DROP TABLE IF EXISTS "zFllw-up-tbl_H-SiteCodes";

CREATE TABLE "zFllw-up-tbl_H-SiteCodes" (
    "Spec_Code" INTEGER,
    "Special" TEXT
);

INSERT INTO "zFllw-up-tbl_H-SiteCodes"("Spec_Code","Special")
VALUES(0,NULL);
INSERT INTO "zFllw-up-tbl_H-SiteCodes"("Spec_Code","Special")
VALUES(1,'Phone');
INSERT INTO "zFllw-up-tbl_H-SiteCodes"("Spec_Code","Special")
VALUES(2,'IDOC');
INSERT INTO "zFllw-up-tbl_H-SiteCodes"("Spec_Code","Special")
VALUES(3,'CCJ');
INSERT INTO "zFllw-up-tbl_H-SiteCodes"("Spec_Code","Special")
VALUES(4,'Pick-up');
INSERT INTO "zFllw-up-tbl_H-SiteCodes"("Spec_Code","Special")
VALUES(5,'Site');
INSERT INTO "zFllw-up-tbl_H-SiteCodes"("Spec_Code","Special")
VALUES(6,'DCJ');
INSERT INTO "zFllw-up-tbl_H-SiteCodes"("Spec_Code","Special")
VALUES(7,'Incarcerated');



DROP TABLE IF EXISTS "zFllw-up-tbl_M-Mail status";

CREATE TABLE "zFllw-up-tbl_M-Mail status" (
    "MailCode" INTEGER,
    "Text" TEXT
);

INSERT INTO "zFllw-up-tbl_M-Mail status"("MailCode","Text")
VALUES(0,'Not mailed');
INSERT INTO "zFllw-up-tbl_M-Mail status"("MailCode","Text")
VALUES(1,'Mailed');
INSERT INTO "zFllw-up-tbl_M-Mail status"("MailCode","Text")
VALUES(3,'Returned');
INSERT INTO "zFllw-up-tbl_M-Mail status"("MailCode","Text")
VALUES(4,'Contact-info only');



DROP TABLE IF EXISTS "zFllw-up-tbl_N-Relationship";

CREATE TABLE "zFllw-up-tbl_N-Relationship" (
    "Rel_code" INTEGER,
    "Relationship" TEXT
);

INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(100,'Client');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(101,'Mother-Step');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(103,'Spouse - Partner');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(104,'Grandmother');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(108,'Aunt');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(106,'Sister - Brother');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(107,'Cousin');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(110,'Child-1');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(111,'Child-2');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(102,'Father-Step');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(199,'Other family member');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(200,'Friend');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(202,'Girlfriend');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(203,'Copping Buddy - Running Partner');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(204,'Neighbor');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(301,'Counselor');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(401,'DCFS Caseworker');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(402,'Parole - Probation Officer');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(499,'Other contact');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(500,'Tx Facility');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(700,'Criminal Justice');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(105,'Grandfather');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(109,'Uncle');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(201,'Boyfriend');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(205,'In-laws');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(501,'Shelter');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(300,'Employer');
INSERT INTO "zFllw-up-tbl_N-Relationship"("Rel_code","Relationship")
VALUES(502,'Recovery House');



DROP TABLE IF EXISTS "zFllw-up-tbl_P-SchedCodes";

CREATE TABLE "zFllw-up-tbl_P-SchedCodes" (
    "Interview status code" INTEGER,
    "Intvw status" TEXT
);

INSERT INTO "zFllw-up-tbl_P-SchedCodes"("Interview status code","Intvw status")
VALUES(0,'Not complete');
INSERT INTO "zFllw-up-tbl_P-SchedCodes"("Interview status code","Intvw status")
VALUES(600,'Complete');
INSERT INTO "zFllw-up-tbl_P-SchedCodes"("Interview status code","Intvw status")
VALUES(300,'No show');
INSERT INTO "zFllw-up-tbl_P-SchedCodes"("Interview status code","Intvw status")
VALUES(605,'Incomplete');
INSERT INTO "zFllw-up-tbl_P-SchedCodes"("Interview status code","Intvw status")
VALUES(500,'Rescheduled');



DROP TABLE IF EXISTS "zFllw-up-tbl_Q-SpecPopCodes";

CREATE TABLE "zFllw-up-tbl_Q-SpecPopCodes" (
    "SpecCode" INTEGER,
    "SpecPop" TEXT
);

INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(0,NULL);
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(501,'Hispanic');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(502,'Homeless');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(504,'Mentally ill');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(500,'Incarcerated');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(503,'Chronically ill');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(505,'In treatment');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(511,'Out of state');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(506,'CCJ');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(507,'IDOC');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(508,'Incarcerated, in Illinois');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(509,'Incarcerated, out of state');
INSERT INTO "zFllw-up-tbl_Q-SpecPopCodes"("SpecCode","SpecPop")
VALUES(510,'DCJ');



DROP TABLE IF EXISTS "zFllw-up-tbl_R-ClientStatusCodes";

CREATE TABLE "zFllw-up-tbl_R-ClientStatusCodes" (
    "StatCode" INTEGER,
    "ClientStatus" TEXT
);

INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(100,'Not scheduled');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(620,'Lost-Not Found');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(600,'Completed');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(602,'Deceased');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(601,'Refused');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(150,'Scheduled');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(175,'Confirmed');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(625,'Lost-Out of Time');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(506,'CCJ');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(507,'IDOC');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(508,'Incarcerated');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(800,'Removed from Study');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(200,'Past Due');
INSERT INTO "zFllw-up-tbl_R-ClientStatusCodes"("StatCode","ClientStatus")
VALUES(750,'Medically unable to complete interview');



DROP TABLE IF EXISTS "zFllw-up-tbl_S-True-FalseCodes";

CREATE TABLE "zFllw-up-tbl_S-True-FalseCodes" (
    "TrueFalse Code" INTEGER,
    "Code_V" TEXT,
    "DischCode" TEXT
);

INSERT INTO "zFllw-up-tbl_S-True-FalseCodes"("TrueFalse Code","Code_V","DischCode")
VALUES(0,'No',NULL);
INSERT INTO "zFllw-up-tbl_S-True-FalseCodes"("TrueFalse Code","Code_V","DischCode")
VALUES(-1,'Yes',NULL);



DROP TABLE IF EXISTS "zFllw-up-tbl_T-ContactStatCodes";

CREATE TABLE "zFllw-up-tbl_T-ContactStatCodes" (
    "CtctCodes" INTEGER,
    "Status" TEXT
);

INSERT INTO "zFllw-up-tbl_T-ContactStatCodes"("CtctCodes","Status")
VALUES(0,'Usable');
INSERT INTO "zFllw-up-tbl_T-ContactStatCodes"("CtctCodes","Status")
VALUES(1,'Bad Information');
INSERT INTO "zFllw-up-tbl_T-ContactStatCodes"("CtctCodes","Status")
VALUES(2,'Hostile Contact');
INSERT INTO "zFllw-up-tbl_T-ContactStatCodes"("CtctCodes","Status")
VALUES(3,'Temporary Unusable');



DROP TABLE IF EXISTS "zFllw-up-tbl_U-WaveCodes";

CREATE TABLE "zFllw-up-tbl_U-WaveCodes" (
    "Codes" INTEGER,
    "Waves" TEXT,
    "Std" TEXT
);

INSERT INTO "zFllw-up-tbl_U-WaveCodes"("Codes","Waves","Std")
VALUES(3,'3mth','SARC-CL');
INSERT INTO "zFllw-up-tbl_U-WaveCodes"("Codes","Waves","Std")
VALUES(4,'6mth','SARC-CL');
INSERT INTO "zFllw-up-tbl_U-WaveCodes"("Codes","Waves","Std")
VALUES(0,NULL,'SARC-CL');
INSERT INTO "zFllw-up-tbl_U-WaveCodes"("Codes","Waves","Std")
VALUES(1,'Wk1','SARC-CL');
INSERT INTO "zFllw-up-tbl_U-WaveCodes"("Codes","Waves","Std")
VALUES(2,'Wk3','SARC-CL');
INSERT INTO "zFllw-up-tbl_U-WaveCodes"("Codes","Waves","Std")
VALUES(5,'9mth','SARC-CL');
INSERT INTO "zFllw-up-tbl_U-WaveCodes"("Codes","Waves","Std")
VALUES(-1,'PreRandomization','SARC-CL');
INSERT INTO "zFllw-up-tbl_U-WaveCodes"("Codes","Waves","Std")
VALUES(9,'PostRandomization','SARC-CL');


