-- SQL Dump of gRand.mdb
-- generated by MDB Viewer 2.2.7
-- optimized for SQLite


DROP TABLE IF EXISTS "RAlgLabels";

CREATE TABLE "RAlgLabels" (
    "RAlg" INTEGER PRIMARY KEY,
    "RAlgLabel" TEXT
);

INSERT INTO "RAlgLabels"("RAlg","RAlgLabel")
VALUES(1,'Permuted Block');
INSERT INTO "RAlgLabels"("RAlg","RAlgLabel")
VALUES(2,'Urn');



DROP TABLE IF EXISTS "SimResults";

CREATE TABLE "SimResults" (
    "BSeq" INTEGER PRIMARY KEY,
    "Alpha" INTEGER,
    "Beta" INTEGER,
    "n1" INTEGER,
    "n2" INTEGER,
    "n3" INTEGER,
    "n4" INTEGER,
    "Imbalance" INTEGER
);

INSERT INTO "SimResults"("BSeq","Alpha","Beta","n1","n2","n3","n4","Imbalance")
VALUES(1568,1,32767,49,49,54,48,8);



DROP TABLE IF EXISTS "State";

CREATE TABLE "State" (
    "ProjectNumber" INTEGER,
    "UserName" TEXT,
    "ProjectID" TEXT,
    "DateTimeStamp" DATETIME
);

INSERT INTO "State"("ProjectNumber","UserName","ProjectID","DateTimeStamp")
VALUES(6,'Rod','0001','2020-01-16 12:36:24');
INSERT INTO "State"("ProjectNumber","UserName","ProjectID","DateTimeStamp")
VALUES(3,'Belinda','693','2015-03-12 00:00:00');


